default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: lunch_roulette_development
  username: <%= ENV['LOCAL_USERNAME'] %>
  password:

test:
  <<: *default
  database: lunch_roulette_test
  username: <%= ENV['LOCAL_USERNAME'] %>
  password:
