# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74b63827bbb7f88836da880ad4f091fd41be194562204f80cca5a13e525ce710e919a5ce1469335fb433329e3b741ac48b74390e3dceaa591c8f8ae93e4b9dfc

test:
  secret_key_base: 725a8aaf41423cdc31c87589fc14399d3b3d220f693da88d359088496de7842cb7e0804d38a3cce3fb3d01c7cf6a8e43ca4b47c9f7279339f4353a47fde8425f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
